### ISSUE TITLE
use roles for distinguishing task between OS

### ISSUE THREAD

**Issue by KatKmiotek** [KatKmiotek/ansible_setup_mac#6]
- folder structure change:
 setup.yml - to gather facts on os 
roles/windows/tasks/...yml
roles/macos/tasks/...yml
vars... possibly remain in root

- use host information to distinguish between darwin and windows 
```yml
roles:
    - role: windows
      when: ansible_os_family == "Windows"
```
- identify tasks that are OS-agnostic

out of scope: 
- implementing windows specific tasks
